apiVersion: v2
name: pucora
description: Helm chart for deploying the Pucora API Gateway on Kubernetes
type: application
version: 2.2.0
appVersion: "2.2.0"
keywords:
  - api-gateway
  - pucora
  - microservices
home: https://pucora.io
sources:
  - https://github.com/pucora/velonetics-ce
maintainers:
  - name: Pucora Team
    email: community@pucora.io
