// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: flights.proto

package flight_finder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_flights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_flights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_flights_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type When struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departure     string                 `protobuf:"bytes,1,opt,name=departure,proto3" json:"departure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *When) Reset() {
	*x = When{}
	mi := &file_flights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *When) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*When) ProtoMessage() {}

func (x *When) ProtoReflect() protoreflect.Message {
	mi := &file_flights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use When.ProtoReflect.Descriptor instead.
func (*When) Descriptor() ([]byte, []int) {
	return file_flights_proto_rawDescGZIP(), []int{1}
}

func (x *When) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

type FindFlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Where         *Location              `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	When          *When                  `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFlightRequest) Reset() {
	*x = FindFlightRequest{}
	mi := &file_flights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFlightRequest) ProtoMessage() {}

func (x *FindFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFlightRequest.ProtoReflect.Descriptor instead.
func (*FindFlightRequest) Descriptor() ([]byte, []int) {
	return file_flights_proto_rawDescGZIP(), []int{2}
}

func (x *FindFlightRequest) GetWhere() *Location {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *FindFlightRequest) GetWhen() *When {
	if x != nil {
		return x.When
	}
	return nil
}

type Flight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_flights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_flights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_flights_proto_rawDescGZIP(), []int{3}
}

func (x *Flight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flight) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type FindFlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flights       []*Flight              `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFlightResponse) Reset() {
	*x = FindFlightResponse{}
	mi := &file_flights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFlightResponse) ProtoMessage() {}

func (x *FindFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFlightResponse.ProtoReflect.Descriptor instead.
func (*FindFlightResponse) Descriptor() ([]byte, []int) {
	return file_flights_proto_rawDescGZIP(), []int{4}
}

func (x *FindFlightResponse) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

var File_flights_proto protoreflect.FileDescriptor

const file_flights_proto_rawDesc = "" +
	"\n" +
	"\rflights.proto\x12\rflight_finder\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"$\n" +
	"\x04When\x12\x1c\n" +
	"\tdeparture\x18\x01 \x01(\tR\tdeparture\"k\n" +
	"\x11FindFlightRequest\x12-\n" +
	"\x05where\x18\x01 \x01(\v2\x17.flight_finder.LocationR\x05where\x12'\n" +
	"\x04when\x18\x02 \x01(\v2\x13.flight_finder.WhenR\x04when\":\n" +
	"\x06Flight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"E\n" +
	"\x12FindFlightResponse\x12/\n" +
	"\aflights\x18\x01 \x03(\v2\x15.flight_finder.FlightR\aflights2\\\n" +
	"\aFlights\x12Q\n" +
	"\n" +
	"FindFlight\x12 .flight_finder.FindFlightRequest\x1a!.flight_finder.FindFlightResponseBAZ?github.com/pucora/velonetics-grpc/v2/testdata/flight_finderb\x06proto3"

var (
	file_flights_proto_rawDescOnce sync.Once
	file_flights_proto_rawDescData []byte
)

func file_flights_proto_rawDescGZIP() []byte {
	file_flights_proto_rawDescOnce.Do(func() {
		file_flights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flights_proto_rawDesc), len(file_flights_proto_rawDesc)))
	})
	return file_flights_proto_rawDescData
}

var file_flights_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flights_proto_goTypes = []any{
	(*Location)(nil),           // 0: flight_finder.Location
	(*When)(nil),               // 1: flight_finder.When
	(*FindFlightRequest)(nil),  // 2: flight_finder.FindFlightRequest
	(*Flight)(nil),             // 3: flight_finder.Flight
	(*FindFlightResponse)(nil), // 4: flight_finder.FindFlightResponse
}
var file_flights_proto_depIdxs = []int32{
	0, // 0: flight_finder.FindFlightRequest.where:type_name -> flight_finder.Location
	1, // 1: flight_finder.FindFlightRequest.when:type_name -> flight_finder.When
	3, // 2: flight_finder.FindFlightResponse.flights:type_name -> flight_finder.Flight
	2, // 3: flight_finder.Flights.FindFlight:input_type -> flight_finder.FindFlightRequest
	4, // 4: flight_finder.Flights.FindFlight:output_type -> flight_finder.FindFlightResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_flights_proto_init() }
func file_flights_proto_init() {
	if File_flights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flights_proto_rawDesc), len(file_flights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flights_proto_goTypes,
		DependencyIndexes: file_flights_proto_depIdxs,
		MessageInfos:      file_flights_proto_msgTypes,
	}.Build()
	File_flights_proto = out.File
	file_flights_proto_goTypes = nil
	file_flights_proto_depIdxs = nil
}
