ARG GOLANG_VERSION
ARG ALPINE_VERSION

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}

RUN apk --no-cache add tar make gcc musl-dev binutils-gold curl \
 && curl -fsSL --retry 5 --retry-delay 10 --retry-all-errors --connect-timeout 30 --max-time 900 \
    -o /aarch64-linux-musl-cross.tgz https://musl.cc/aarch64-linux-musl-cross.tgz \
 && tar zxf /aarch64-linux-musl-cross.tgz -C / \
 && rm -f /aarch64-linux-musl-cross.tgz \
 && apk del curl

ENV PATH="$PATH:/aarch64-linux-musl-cross/bin:/aarch64-linux-musl-cross/aarch64-linux-musl/bin"
