ARG GOLANG_VERSION=1.25.11
FROM golang:${GOLANG_VERSION}-bookworm

RUN apt-get update && \
    apt-get install -y gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
    && rm -rf /var/lib/apt/lists/*
