{{- if and (eq .Values.config.mode "configmap") (not .Values.config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pucora.configMapName" . }}
  labels:
    {{- include "pucora.labels" . | nindent 4 }}
data:
  pucora.json: |
{{- .Values.config.veloneticsJson | nindent 4 }}
{{- end }}
