{{- if and (eq .Values.config.mode "secret") (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pucora.configSecretName" . }}
  labels:
    {{- include "pucora.labels" . | nindent 4 }}
type: Opaque
stringData:
  pucora.json: |
{{- .Values.config.veloneticsJson | nindent 4 }}
{{- end }}
