{{- if .Values.configurator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pucora.configuratorWebName" . }}
  labels:
    {{- include "pucora.labels" . | nindent 4 }}
    app.kubernetes.io/component: configurator-web
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://{{ include "pucora.configuratorApiName" . }}:{{ .Values.configurator.api.service.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
{{- end }}
