{{- if and .Values.configurator.enabled .Values.configurator.api.auth.apiKey (not .Values.configurator.api.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pucora.configuratorApiSecretName" . }}
  labels:
    {{- include "pucora.labels" . | nindent 4 }}
    app.kubernetes.io/component: configurator-api
type: Opaque
stringData:
  {{ .Values.configurator.api.auth.secretKey }}: {{ .Values.configurator.api.auth.apiKey | quote }}
{{- end }}
