{{- if .Values.configurator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pucora.configuratorApiName" . }}
  labels:
    {{- include "pucora.labels" . | nindent 4 }}
    app.kubernetes.io/component: configurator-api
  {{- with .Values.configurator.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.configurator.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pucora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: configurator-api
{{- end }}
